<a href="https://colab.research.google.com/github/CodeVishal-17/guess_the_number/blob/main/DataAnylaticsm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
sentence = "I love Python programing"
sentence.find("P")

7

In [ ]:
name = input("enter your name.: ")
age = int(input("Enter your age. "))
if age >= 18:
  print("you are eligible for driving license")
else:
  print("you are not eligible")

enter your name.: vishal
Enter your age. 19
you are eligible for driving license


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[1,2,3]])
print(a.shape)


(3, 3)


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a.shape(3,3)
a


TypeError: 'tuple' object is not callable

In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
b


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
import numpy as np
a = np.array([[[[1,2,3],[4,5,6]]]])
a.ndim


4

In [ ]:
import numpy as np
a = np.arange(24)
print("array items are:",a)
print("Array dimensions is:",a.ndim)
b = a.reshape(2,4,3)
print("arr after reshape is\n",b)


array items are: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Array dimensions is: 1
arr after reshape is
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [ ]:
import numpy as np
x = np.array([1,2,3,4,5],dtype=np.int8)
print(x.itemsize)

8


In [ ]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x.itemsize)

8


In [ ]:
import numpy as np
x = np.empty([3,2],dtype=int)
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
import numpy as np
x = np.empty([3,2])
x

array([[3.91481274e-315, 0.00000000e+000],
       [3.85681493e-315, 1.63041663e-322],
       [3.91442164e-315, 6.93477890e-310]])

In [ ]:
import numpy as np
x = np.zeros([2,2],dtype=[('x','i4'),('y','i4')])
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [ ]:
import numpy as np
x = np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [ ]:
import numpy as np
x = np.ones([3,3],dtype=int)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
import numpy as np
x = [1,2,3]
a = np.asarray(x)
print(a)

[1 2 3]


In [ ]:
import numpy as np
x = (1,2,3)
a = np.asarray(x)
print(a)

[1 2 3]


In [ ]:
import numpy as np
x = [(1,2,3),(4,5,6)]
a = np.asarray(x)
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
list = range(5)
it = iter(list)
x = np.fromiter(it,dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [ ]:
import numpy as np
lists = range(5)
it = iter(list)
x = np.fromiter(lists,dtype=float)
print(x)

[0. 1. 2. 3. 4.]


In [ ]:
import numpy as np
lists = np.arange(5)
print(lists)

[0 1 2 3 4]


In [ ]:
import numpy as np
lists = np.arange(5,dtype=float)
print(lists)

[0. 1. 2. 3. 4.]


In [ ]:
import numpy as np
lists = np.arange(10,20,2)
print(lists)

[10 12 14 16 18]


In [ ]:
import numpy as np
lists = np.linspace(10,20,5)
print(lists)

[10.  12.5 15.  17.5 20. ]


In [ ]:
import numpy as np
lists = np.linspace(10,20,endpoint=False)
print(lists)

[10.  10.2 10.4 10.6 10.8 11.  11.2 11.4 11.6 11.8 12.  12.2 12.4 12.6
 12.8 13.  13.2 13.4 13.6 13.8 14.  14.2 14.4 14.6 14.8 15.  15.2 15.4
 15.6 15.8 16.  16.2 16.4 16.6 16.8 17.  17.2 17.4 17.6 17.8 18.  18.2
 18.4 18.6 18.8 19.  19.2 19.4 19.6 19.8]


In [ ]:
import numpy as np
lists = np.linspace(10,20,5,endpoint=False)
print(lists)

[10. 12. 14. 16. 18.]


In [ ]:
import numpy as np
lists = np.logspace(1.0,2.0,num=10)
print(lists)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [ ]:
import numpy as np
lists = np.logspace(1,20,num=10)
print(lists)

[1.00000000e+01 1.29154967e+03 1.66810054e+05 2.15443469e+07
 2.78255940e+09 3.59381366e+11 4.64158883e+13 5.99484250e+15
 7.74263683e+17 1.00000000e+20]


In [ ]:
import numpy as np
lists = np.logspace(1,10,num=10,base=2)
print(lists)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [ ]:
import numpy as np
lists = np.logspace(1,10,num=10,base=2)
print(lists)

In [ ]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print("original array is: ")
print(a)
print("\n")
print("modified array is:")
for x in np.nditer(a):
  print(x)

original array is: 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [ ]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print("original array is: ")
print(a)
print("\n")
for x in np.nditer(a,op_flags=['readwrite']):
  x[...] = 2*x
print("modified array is ")
print(a)

original array is: 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


modified array is 
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [ ]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print("original array is: ")
print(a)
print("\n")
print("second array is :")
b = np.array([1,2,3,4],dtype=int)
print(b)
print("\n")
print("modified array is:")
for x,y in np.nditer([a,b]):
  print("%d:%d"%(x,y))

original array is: 
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


second array is :
[1 2 3 4]


modified array is:
0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4


In [ ]:
import numpy as np
scores = [85,90,78,92]
mean_score = np.mean(scores)
print(f"class mean: {mean_score}")

class mean: 86.25


In [ ]:
import numpy as np
data = np.array([85,90,78,92])
max_val = np.max(data)
min_value = np.min(data)
print(f"max value: {max_val},min value: {min_value}")


max value: 92,min value: 78


In [ ]:
import numpy as np
scores = np.array([1,50,78,92])
sd = np.std(scores)
print(f"standard deviation:{sd:.2f}")

standard deviation:34.78


In [ ]:
import PIL
import numpy as np
import requests
from io import BytesIO

# URL of a different image
image_url = "https://via.placeholder.com/600x400.png?text=Placeholder+Image"

# Download the image content
response = requests.get(image_url)
response.raise_for_status() # Raise an HTTPError for bad responses (4xx or 5xx)

# Open the image from the in-memory binary content
img = np.array(PIL.Image.open(BytesIO(response.content)))
print(img.shape)

ConnectionError: HTTPSConnectionPool(host='via.placeholder.com', port=443): Max retries exceeded with url: /600x400.png?text=Placeholder+Image (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7d2004522990>: Failed to resolve 'via.placeholder.com' ([Errno -3] Temporary failure in name resolution)"))

In [ ]:
import PIL
import numpy as np

image_path = '/content/itm_university_gwalior_logo.jpg'

img_local = np.array(PIL.Image.open(image_path))
print(f"Image loaded successfully with shape: {img_local.shape}")

Image loaded successfully with shape: (200, 200, 3)


In [1]:
import numpy as np
u = np.array([1,2,3])
v = np.array([4,5,6])
result = np.dot(u,v)
print(result)

32


In [8]:
import random
print(random.randint(1,6))


6


In [16]:
import random,collections
rolls = [random.randint(1,6) for _ in range(1000)]
print(collections.Counter(rolls))


Counter({1: 201, 6: 188, 4: 167, 3: 157, 5: 145, 2: 142})


In [20]:
import random,collections
rolls = [random.randint(1,6)+random.randint(1,6)for _ in range(10000)]
print(collections.Counter(rolls).most_common(3))

[(7, 1654), (6, 1420), (8, 1411)]


In [27]:
import random,collections,numpy as np
rolls = np.random.rand(100,1000)
print(rolls)

[[0.76922728 0.35490953 0.47685659 ... 0.93499689 0.15488161 0.19022658]
 [0.10222626 0.34119212 0.08451313 ... 0.4934534  0.34434208 0.47462134]
 [0.38778575 0.69587516 0.70918468 ... 0.15557997 0.55489809 0.13491348]
 ...
 [0.30836896 0.59840745 0.59933124 ... 0.77537844 0.15717501 0.98945282]
 [0.62266328 0.41206776 0.55728081 ... 0.63686682 0.29290369 0.07658307]
 [0.99226872 0.200308   0.88285619 ... 0.02046475 0.16571415 0.00477612]]


In [31]:
import random,collections,numpy as np

states = ["sunny","rainy"]
trans = [["0.7","0.3"],["0.4","0.6"]]
current = "sunny"
for _ in range(5):
  current = np.random.choice(states,p=trans[states.index(current)])
print(current)

sunny


In [ ]:
import random,collections,numpy as np
states = ["sunny","rainy"]
trans = [["0.7","0.3"],["0.4","0.6"]]
current = "sunny"
for _ in range(5):
  current = np.random.choice(states,p=trans[states.index(current)])
print(current)