<a href="https://colab.research.google.com/github/CodeVishal-17/guess_the_number/blob/main/Module2_Activity2_1_NumPy_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Course: Data Analytics Using Python (AIL0202)
## Module 2 – Activity 2.1
### NumPy Hands-on Lab (5 Marks)


### Instructions:
- Complete all tasks.
- Run each cell and show outputs.
- Add comments wherever required.
- Submit the completed notebook(PDF) on LMS.

Name:Vishal Goyal

Roll No.:BETN1AI25107


In [1]:
# Import NumPy
import numpy as np
print('NumPy Version:', np.__version__)


NumPy Version: 2.0.2


## Task 1: Array Creation(1 Mark)

Create:

1D array of 10 integers

2D array (3×3 matrix)

Identity matrix of size 4

Random array (5×5)

In [12]:
import numpy as np
import random

# Create required arrays here

# 1D array of 10 integers
array_1d = np.arange(1, 11)
print(array_1d)
print("\n")

# 3x3 matrix
matrix_3x3 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(matrix_3x3)
print("\n")

# Identity matrix of size 4
identity_matrix = np.eye(4)
print(identity_matrix)
print("\n")

# Random 5x5 matrix
random_matrix = np.random.randint(0, 10, (5, 5))
print(random_matrix)
print("\n")



[ 1  2  3  4  5  6  7  8  9 10]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[[2 4 9 1 4]
 [8 0 1 2 8]
 [0 0 7 5 7]
 [5 4 9 6 0]
 [9 5 1 8 2]]




## Task 2: Indexing & Slicing (1 Mark)

Given:

A = np.arange(1, 26).reshape(5,5)

Perform:

Extract 2nd row

Extract 3rd column

Extract 2×2 submatrix (center)

Reverse last row

In [16]:
import numpy as np

A = np.arange(1, 26).reshape(5,5)
print(A)
print("\n")

# Extract 2nd row
print(A[1])
print("\n")

# Extract 3rd column
print(A[:, 2])
print("\n")

# Extract 2x2 center matrix
print(A[1:3, 1:3])
print("\n")

# Reverse last row
print(A[-1][::-1])
print("\n")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


[ 6  7  8  9 10]


[ 3  8 13 18 23]


[[ 7  8]
 [12 13]]


[25 24 23 22 21]




## Task 3: Broadcasting(1 Mark)

Perform broadcasting operations on matrix A created in Task-2.

Add scalar 10 to matrix A

Add vector [1,2,3,4,5] to each row

Normalize matrix values between 0–1

In [15]:
import numpy as np

A = np.arange(1, 26).reshape(5,5)
print(A)

# Perform broadcasting operations here

# Add scalar 10 to matrix
print("\nAdd scalar 10 to matrix:\n", A + 10)

# Add vector [1,2,3,4,5] to each row
print("\nAdd vector [1,2,3,4,5] to each row:", A + np.array([1,2,3,4,5]))

# Normalize matrix between 0 and 1
normalized_A = (A - A.min()) / (A.max() - A.min())
print("\nNormalized matrix between 0 and 1:", normalized_A)

Original Matrix A:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Add scalar 10 to matrix:
 [[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]

Add vector [1,2,3,4,5] to each row:
 [[ 2  4  6  8 10]
 [ 7  9 11 13 15]
 [12 14 16 18 20]
 [17 19 21 23 25]
 [22 24 26 28 30]]

Normalized matrix between 0 and 1:
 [[0.         0.04166667 0.08333333 0.125      0.16666667]
 [0.20833333 0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.45833333 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.70833333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.95833333 1.        ]]


## Task 4: Vectorized Computation(1 Marks)

Perform element-wise multiplication
Compute dot product
Compute mean, standard deviation

In [20]:
import numpy as np

X = np.array([1,2,3,4])
Y = np.array([5,6,7,8])

# Element-wise multiplication
print(f"Element-wise multiplication:{X*Y}\n")

# Dot product
x_y_dot = np.dot(X,Y)
print(f"Dot product:{x_y_dot}\n")

# Mean and Standard Deviation
x_mean = np.mean(X)
print(f"Mean of X:{x_mean}\n")
x_standard = np.std(X)
print(f"Standard Deviation of X:{x_standard}\n")
y_mean = np.mean(Y)
print(f"Mean of Y:{y_mean}\n")
y_standard = np.std(Y)
print(f"Standard Deviation of Y:{y_standard}\n")

Element-wise multiplication:[ 5 12 21 32]

Dot product:70

Mean of X:2.5

Standard Deviation of X:1.118033988749895

Mean of Y:6.5

Standard Deviation of Y:1.118033988749895



Task 5: Mini Case Problem (1 Mark)

Dataset: Student marks (5 students, 3 subjects)

Compute total and average per student

Find topper

Find subject-wise highest score

In [21]:
import numpy as np

marks = np.array([[80,75,90],[60,88,70],[95,92,85],[70,65,60],[88,78,84]])

# Compute totals, averages, topper

# Total marks per student
totals = np.sum(marks, axis=1)
print("Total marks per student:", totals)

# Average marks per student
averages = np.mean(marks, axis=1)
print("Average marks per student:", averages)

# Find topper (student with highest total)
topper_index = np.argmax(totals)
print("Topper is student index:", topper_index)
print("Topper total marks:", totals[topper_index])

# Subject-wise highest score
subject_highest = np.max(marks, axis=0)
print("Subject-wise highest scores:", subject_highest)

Total marks per student: [245 218 272 195 250]
Average marks per student: [81.66666667 72.66666667 90.66666667 65.         83.33333333]
Topper is student index: 2
Topper total marks: 272
Subject-wise highest scores: [95 92 90]
