<a href="https://colab.research.google.com/github/CodeVishal-17/guess_the_number/blob/main/Vishal_Goyal_BETN1AI25107_Module_2_lab_base_activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**📘 Module 2 – Numerical & Matrix Computations Using NumPy**

**Data Analytics Using Python (AIL0202)**

Semester II – B.Tech CSE (AIML)

Name - Vishl Goyal

Roll Number = BETN1AI25107

github link:

Collab note book link:

-------------------------------------------------------------------------------
1️⃣ Aim of the Experiment
-------------------------------------------------------------------------------
To perform numerical computations, matrix operations, and statistical analysis using NumPy and apply them to real-world datasets such as student marks, temperature readings, sales data, and electricity load.



**Case Study 1: Student Marks Analysis**
-------------------------------------------------------------------------------

Using NumPy functions such as sum(), mean(), max(), std(), and argmax(), student performance
was analyzed. The topper was identified based on total marks. Subject-wise variation was
examined using standard deviation to measure consistency.


In [1]:
import numpy as np

# Dataset: Marks of 5 students in 3 subjects
marks = np.array([
    [80, 75, 90],
    [60, 88, 70],
    [95, 92, 85],
    [70, 65, 60],
    [88, 78, 84]
])

print("Marks Matrix:\n", marks)

Marks Matrix:
 [[80 75 90]
 [60 88 70]
 [95 92 85]
 [70 65 60]
 [88 78 84]]


In [3]:
#Total Marks of Each Student
total_marks = np.sum(marks, a=1xis)
print("Total Marks of Each Student:", total_marks)

Total Marks of Each Student: [245 218 272 195 250]


In [7]:
#Average Marks Per Student
average_marks = np.mean(marks, axis=1)
print("Average Marks of Each Student:", average_marks)

Average Marks of Each Student: [81.66666667 72.66666667 90.66666667 65.         83.33333333]


In [10]:
#Identify Topper
topper_index = np.argmax(total_marks)
print("Topper is Student", topper_index + 1)

Topper is Student 3


In [11]:
#Subject-wise Highest Score
subject_highest = np.max(marks, axis=0)
print("Highest Score in Each Subject:", subject_highest)

Highest Score in Each Subject: [95 92 90]


In [12]:
#Standard Deviation of Each Subject
subject_std = np.std(marks, axis=0)
print("Standard Deviation of Each Subject:", subject_std)

Standard Deviation of Each Subject: [12.48358923  9.60416576 11.1067547 ]


**Interpretation Of Case 1**
--------------------------------------------------------------------------------

Student 3 has the highest total marks and is the topper.

Subject 1 shows the highest maximum score (95).

Standard deviation indicates moderate variation in performance.

Students show consistent performance, but Subject 2 has slightly higher variability.

**Case Study 3: Sales Analysis**
--------------------------------------------------------------------------------
Aim

To analyze weekly sales data using NumPy statistical functions.

In [13]:
#Create Dataset
sales = np.array([1200, 1500, 1100, 1700, 1600, 1800, 1400])

print("Weekly Sales Data:", sales)

Weekly Sales Data: [1200 1500 1100 1700 1600 1800 1400]


In [14]:
#Average Daily Sales
average_sales = np.mean(sales)
print("Average Daily Sales:", average_sales)

Average Daily Sales: 1471.4285714285713


In [15]:
#Day with Highest Sales
highest_day = np.argmax(sales)
print("Highest Sales on Day:", highest_day + 1)

Highest Sales on Day: 6


In [16]:
#Percentage Growth (Day 1 to Day 7)
percentage_growth = ((sales[-1] - sales[0]) / sales[0]) * 100
print("Percentage Growth from Day 1 to Day 7:", percentage_growth, "%")

Percentage Growth from Day 1 to Day 7: 16.666666666666664 %


In [17]:
#Cumulative Sales
cumulative_sales = np.cumsum(sales)
print("Cumulative Sales:", cumulative_sales)

Cumulative Sales: [ 1200  2700  3800  5500  7100  8900 10300]


In [18]:
#Standard Deviation
sales_std = np.std(sales)
print("Standard Deviation of Sales:", sales_std)

Standard Deviation of Sales: 237.33211036908787


**Interpretation of case 3**
--------------------------------------------------------------------------------

Average daily sales indicate steady revenue generation.

Sales peaked on Day 6.

There is overall growth from Day 1 to Day 7.

Standard deviation suggests moderate variation in daily sales performance.

**Conclusion**
----------------------------------------------------------------------------------------------------------------------------------------------------------------

Insights Derived:

NumPy efficiently performs matrix and statistical computations.

Sales data shows positive growth trend.

Student performance analysis identifies topper and subject consistency.

**Most Useful NumPy Functions:**

1. np.sum()

2. np.mean()

3. np.std()

4. np.argmax()

5. np.cumsum()

**Role of Numerical Computation in Data Analytics:**

Numerical computation allows fast processing of large datasets, helps identify trends, patterns, and variability, and supports data-driven decision making. Vectorized operations in NumPy significantly improve performance compared to manual calculations.